apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      containers:
      - name: api
        image: ergikame/hyra-frontend:apiTest
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                key: DB_PORT
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                key: DATABASE
          - name: PORT
            valueFrom:
              secretKeyRef:
                key: PORT