apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources: 
- namespace.yaml
- ip.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.12.1
    releaseName: metallb
    namespace: metallb-system
    valuesFile: values.yaml
    includeCRDs: true