# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-cluster-issuer
#   # namespace: cert-manager
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: ergi@motomtech.com
#     privateKeySecretRef:
#       name: letsencrypt-cluster-issuer-key
#     solvers:
#     - http01:
#        ingress:
#          class: nginx


# For self signed certificates

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}