apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml

helmCharts:
- name: postgresql
  repo: https://charts.bitnami.com/postgresql
  version: 11.6.21
  valuesFile: values.yaml
  releaseName: postgresql
  namespace: postgres